# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25fffd9469f5c87b8b287bcd12544bad4e7d9f42b36670bfb8b66853ce5ebd227572fb5720c4a1e2e606762b0e3160f91d9c656ce6f65ba7e0fbaba9c753e88f

test:
  secret_key_base: 2e0bb7d75330ccf8a3e1297a2fba4a9f9d5a64749d6aa279643626474c9c4c79aeeee6e6be36ed3c4bd676b19b80f412040a9854cd88555b9a4a7794d450b228

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
